openapi: 3.0.0
info:
  title: Webex Admin Address Book BroadWorks Workspaces API
  version: 1.0.0
  description: The Webex Admin APIs provide comprehensive programmatic access to administrative functions for managing Webex organizations, users, licenses, and settings. These APIs enable automation of user provisioning, license assignment, compliance management, and audit event retrieval. Administrators can integrate with enterprise identity systems, enforce security policies, monitor usage, and streamline onboarding/offboarding processes. The APIs support granular control over organizational resources, making them ideal for large-scale deployments and custom admin tooling.
tags:
- name: BroadWorks Workspaces
  description: APIs for managing BroadWorks Workspaces.
paths:
  /broadworks/workspaces:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceResponse'
              example:
                id: Y2lzY29zcGFyazovL3VzL1BMQUNFL2RkMjJlZGZlLTlmZWYtNDdmOS05ODFkLWYxYjA3MWFmMDcwYw
                provisioningId: ZjViMzYxODctYzhkZC00NzI3LThiMmYtZjljNDQ3ZjI5MDQ2OjQyODVmNTk0LTViNTEtNDdiZS05Mzk2LTZjMzZlMmFkODNhNQ
                userId: 95547321@sp.com
                spEnterpriseId: Reseller1+acme
                displayName: Conference Room
                primaryPhoneNumber: +1-240-555-1212
                extension: '51212'
                created: '2019-10-18T14:26:16.000Z'
        '400':
          description: 'Bad Request: The request was invalid or cannot be otherwise served. An accompanying error message will explain further.'
        '401':
          description: 'Unauthorized: Authentication credentials were missing or incorrect.'
        '403':
          description: 'Forbidden: The request is understood, but it has been refused or access is not allowed.'
        '404':
          description: 'Not Found: The URI requested is invalid or the resource requested, such as a user, does not exist. Also returned when the requested format is not supported by the requested method.'
        '405':
          description: 'Method Not Allowed: The request was made to a resource using an HTTP request method that is not supported.'
        '409':
          description: 'Conflict: The request could not be processed because it conflicts with some established rule of the system. For example, a person may not be added to a room more than once.'
        '410':
          description: 'Gone: The requested resource is no longer available.'
        '415':
          description: 'Unsupported Media Type: The request was made to a resource without specifying a media type or used a media type that is not supported.'
        '423':
          description: 'Locked: The requested resource is temporarily unavailable. A Retry-After header may be present that specifies how many seconds you need to wait before attempting the request again.'
        '428':
          description: 'Precondition Required: File(s) cannot be scanned for malware and need to be force downloaded.'
        '429':
          description: 'Too Many Requests: Too many requests have been sent in a given amount of time and the request has been rate limited. A Retry-After header should be present that specifies how many seconds you need to wait before a successful request can be made.'
        '500':
          description: 'Internal Server Error: Something went wrong on the server. If the issue persists, feel free to contact the [Webex Developer Support team](/explore/support).'
        '502':
          description: 'Bad Gateway: The server received an invalid response from an upstream server while processing the request. Try again later.'
        '503':
          description: 'Service Unavailable: Server is overloaded with requests. Try again later.'
        '504':
          description: 'Gateway Timeout: An upstream server failed to respond on time. If your query uses max parameter, please try to reduce it.'
      summary: Provision a BroadWorks Workspace
      operationId: provisionBroadWorksWorkspace
      description: 'Provision a new BroadWorks workspace for Cisco Webex services.


        This API allows a Service Provider to provision a workspace for an existing customer.'
      tags:
      - BroadWorks Workspaces
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              provisioningId: ZjViMzYxODctYzhkZC00NzI3LThiMmYtZjljNDQ3ZjI5MDQ2OjQyODVmNTk0LTViNTEtNDdiZS05Mzk2LTZjMzZlMmFkODNhNQ
              userId: 95547321@sp.com
              spEnterpriseId: Reseller1+acme
              displayName: Conference Room
              primaryPhoneNumber: +1-240-555-1212
              extension: '51212'
            schema:
              type: object
              required:
              - provisioningId
              - userId
              - spEnterpriseId
              - displayName
              properties:
                provisioningId:
                  type: string
                  example: ZjViMzYxODctYzhkZC00NzI3LThiMmYtZjljNDQ3ZjI5MDQ2OjQyODVmNTk0LTViNTEtNDdiZS05Mzk2LTZjMzZlMmFkODNhNQ
                  description: Provisioning ID that defines how this workspace is to be provisioned for Cisco Webex Services. Each Customer Template will have their own unique Provisioning ID. This ID will be displayed under the chosen Customer Template on Cisco Webex Control Hub.
                userId:
                  type: string
                  example: 95547321@sp.com
                  description: The user ID of the workspace on BroadWorks.
                spEnterpriseId:
                  type: string
                  example: Reseller1+acme
                  description: The Service Provider supplied unique identifier for the workspace's enterprise.
                displayName:
                  type: string
                  example: Conference Room
                  description: The display name of the workspace.
                primaryPhoneNumber:
                  type: string
                  example: +1-240-555-1212
                  description: The primary phone number configured against the workspace on BroadWorks.
                extension:
                  type: string
                  example: '51212'
                  description: The extension number configured against the workspace on BroadWorks.
  /broadworks/workspaces/{workspaceId}:
    put:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceResponse'
              example:
                id: Y2lzY29zcGFyazovL3VzL1BMQUNFL2RkMjJlZGZlLTlmZWYtNDdmOS05ODFkLWYxYjA3MWFmMDcwYw
                provisioningId: ZjViMzYxODctYzhkZC00NzI3LThiMmYtZjljNDQ3ZjI5MDQ2OjQyODVmNTk0LTViNTEtNDdiZS05Mzk2LTZjMzZlMmFkODNhNQ
                userId: 95547321@sp.com
                spEnterpriseId: Reseller1+acme
                displayName: Conference Room
                primaryPhoneNumber: +1-240-555-1212
                extension: '51212'
                created: '2019-10-18T14:26:16.000Z'
        '400':
          description: 'Bad Request: The request was invalid or cannot be otherwise served. An accompanying error message will explain further.'
        '401':
          description: 'Unauthorized: Authentication credentials were missing or incorrect.'
        '403':
          description: 'Forbidden: The request is understood, but it has been refused or access is not allowed.'
        '404':
          description: 'Not Found: The URI requested is invalid or the resource requested, such as a user, does not exist. Also returned when the requested format is not supported by the requested method.'
        '405':
          description: 'Method Not Allowed: The request was made to a resource using an HTTP request method that is not supported.'
        '409':
          description: 'Conflict: The request could not be processed because it conflicts with some established rule of the system. For example, a person may not be added to a room more than once.'
        '410':
          description: 'Gone: The requested resource is no longer available.'
        '415':
          description: 'Unsupported Media Type: The request was made to a resource without specifying a media type or used a media type that is not supported.'
        '423':
          description: 'Locked: The requested resource is temporarily unavailable. A Retry-After header may be present that specifies how many seconds you need to wait before attempting the request again.'
        '428':
          description: 'Precondition Required: File(s) cannot be scanned for malware and need to be force downloaded.'
        '429':
          description: 'Too Many Requests: Too many requests have been sent in a given amount of time and the request has been rate limited. A Retry-After header should be present that specifies how many seconds you need to wait before a successful request can be made.'
        '500':
          description: 'Internal Server Error: Something went wrong on the server. If the issue persists, feel free to contact the [Webex Developer Support team](/explore/support).'
        '502':
          description: 'Bad Gateway: The server received an invalid response from an upstream server while processing the request. Try again later.'
        '503':
          description: 'Service Unavailable: Server is overloaded with requests. Try again later.'
        '504':
          description: 'Gateway Timeout: An upstream server failed to respond on time. If your query uses max parameter, please try to reduce it.'
      summary: Update a Broadworks Workspace
      operationId: updateBroadworksWorkspace
      description: Update certain details of a provisioned BroadWorks workspace on Cisco Webex.
      tags:
      - BroadWorks Workspaces
      parameters:
      - name: workspaceId
        in: path
        description: A unique Cisco identifier for the workspace.
        required: true
        example: Y2lzY29zcGFyazovL3VzL1BMQUNFL2RkMjJlZGZlLTlmZWYtNDdmOS05ODFkLWYxYjA3MWFmMDcwYw
        schema:
          type: string
          minLength: 1
          maxLength: 256
      requestBody:
        content:
          application/json:
            example:
              userId: 95547321@sp.com
              primaryPhoneNumber: +1-240-555-1212
              extension: '51212'
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: 95547321@sp.com
                  description: The user ID of the workspace on BroadWorks.
                primaryPhoneNumber:
                  type: string
                  example: +1-240-555-1212
                  description: The primary phone number configured against the workspace on BroadWorks.
                extension:
                  type: string
                  example: '51212'
                  description: The extension number configured against the workspace on BroadWorks.
    delete:
      responses:
        '204':
          description: No Content
          headers: {}
          content: {}
        '400':
          description: 'Bad Request: The request was invalid or cannot be otherwise served. An accompanying error message will explain further.'
        '401':
          description: 'Unauthorized: Authentication credentials were missing or incorrect.'
        '403':
          description: 'Forbidden: The request is understood, but it has been refused or access is not allowed.'
        '404':
          description: 'Not Found: The URI requested is invalid or the resource requested, such as a user, does not exist. Also returned when the requested format is not supported by the requested method.'
        '405':
          description: 'Method Not Allowed: The request was made to a resource using an HTTP request method that is not supported.'
        '409':
          description: 'Conflict: The request could not be processed because it conflicts with some established rule of the system. For example, a person may not be added to a room more than once.'
        '410':
          description: 'Gone: The requested resource is no longer available.'
        '415':
          description: 'Unsupported Media Type: The request was made to a resource without specifying a media type or used a media type that is not supported.'
        '423':
          description: 'Locked: The requested resource is temporarily unavailable. A Retry-After header may be present that specifies how many seconds you need to wait before attempting the request again.'
        '428':
          description: 'Precondition Required: File(s) cannot be scanned for malware and need to be force downloaded.'
        '429':
          description: 'Too Many Requests: Too many requests have been sent in a given amount of time and the request has been rate limited. A Retry-After header should be present that specifies how many seconds you need to wait before a successful request can be made.'
        '500':
          description: 'Internal Server Error: Something went wrong on the server. If the issue persists, feel free to contact the [Webex Developer Support team](/explore/support).'
        '502':
          description: 'Bad Gateway: The server received an invalid response from an upstream server while processing the request. Try again later.'
        '503':
          description: 'Service Unavailable: Server is overloaded with requests. Try again later.'
        '504':
          description: 'Gateway Timeout: An upstream server failed to respond on time. If your query uses max parameter, please try to reduce it.'
      summary: Remove a BroadWorks Workspace
      operationId: removeBroadWorksWorkspace
      description: Remove the mapping between a BroadWorks workspace and Cisco Webex device.
      tags:
      - BroadWorks Workspaces
      parameters:
      - name: workspaceId
        in: path
        description: A unique Cisco identifier for the workspace.
        required: true
        example: Y2lzY29zcGFyazovL3VzL1BMQUNFL2RkMjJlZGZlLTlmZWYtNDdmOS05ODFkLWYxYjA3MWFmMDcwYw
        schema:
          type: string
          minLength: 1
          maxLength: 256
components:
  schemas:
    WorkspaceResponse:
      type: object
      example:
        id: Y2lzY29zcGFyazovL3VzL1BMQUNFL2RkMjJlZGZlLTlmZWYtNDdmOS05ODFkLWYxYjA3MWFmMDcwYw
        provisioningId: ZjViMzYxODctYzhkZC00NzI3LThiMmYtZjljNDQ3ZjI5MDQ2OjQyODVmNTk0LTViNTEtNDdiZS05Mzk2LTZjMzZlMmFkODNhNQ
        userId: 95547321@sp.com
        spEnterpriseId: Reseller1+acme
        displayName: Conference Room
        primaryPhoneNumber: +1-240-555-1212
        extension: '51212'
        created: '2019-10-18T14:26:16.000Z'
      properties:
        provisioningId:
          type: string
          example: ZjViMzYxODctYzhkZC00NzI3LThiMmYtZjljNDQ3ZjI5MDQ2OjQyODVmNTk0LTViNTEtNDdiZS05Mzk2LTZjMzZlMmFkODNhNQ
          description: Provisioning ID that defines how this workspace is to be provisioned for Cisco Webex Services. Each Customer Template will have their own unique Provisioning ID. This ID will be displayed under the chosen Customer Template on Cisco Webex Control Hub.
        userId:
          type: string
          example: 95547321@sp.com
          description: The user ID of the workspace on BroadWorks.
        spEnterpriseId:
          type: string
          example: Reseller1+acme
          description: The Service Provider supplied unique identifier for the workspace's enterprise.
        displayName:
          type: string
          example: Conference Room
          description: The display name of the workspace.
        primaryPhoneNumber:
          type: string
          example: +1-240-555-1212
          description: The primary phone number configured against the workspace on BroadWorks.
        extension:
          type: string
          example: '51212'
          description: The extension number configured against the workspace on BroadWorks.
        id:
          type: string
          example: Y2lzY29zcGFyazovL3VzL1BMQUNFL2RkMjJlZGZlLTlmZWYtNDdmOS05ODFkLWYxYjA3MWFmMDcwYw
          description: A unique Cisco identifier for the workspace.
        created:
          type: string
          example: '2019-10-18T14:26:16.000Z'
          description: The date and time the workspace was provisioned.
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: /
          scopes: {}
          tokenUrl: /
      type: oauth2
    bearer-key:
      type: http
      description: e.g. Bearer YOUR_AUTHORIZATION_TOKEN
      scheme: bearer
      bearerFormat: JWT
    bearerAuth:
      type: oauth2
      description: OAuth 2.0 Bearer token authentication
      flows:
        authorizationCode:
          authorizationUrl: https://webexapis.com/v1/authorize
          tokenUrl: https://webexapis.com/v1/access_token
          scopes:
            spark:applications_token: Create access tokens for Service Apps
